### ISSUE TITLE
Поправить кодировку

### ISSUE THREAD

**Issue by pingvin1308** [barnet30/scheduler#1]
https://github.com/barnet30/scheduler/blob/59909b8322f89de06767d74031031ef8095caf81/scheduler/Startup.cs#L32

Следует избегать использование кодировки не UTF-8 в программном коде

Вот к примеру как выглядит комментарий у меня. Также он будет выглядеть и у твоих коллег
![image](https://user-images.githubusercontent.com/17434920/117459636-4b472700-af54-11eb-89a7-523b3e939456.png)

**Comment by barnet30** [comment]
Поправил
