### ISSUE TITLE
Убрать излишнюю вложенность в методах

### ISSUE THREAD

**Issue by pingvin1308** [barnet30/scheduler#4]
https://github.com/barnet30/scheduler/blob/59909b8322f89de06767d74031031ef8095caf81/scheduler/Controllers/AccountController.cs#L57

Сейчас в коде много где присутствуют вложенные конструкции. Обычно такого подхода стараются избегать, так как это затрудняет чтение кода.

В большинстве случаях, которые я обнаружил в коде можно решить все с помощью инверсии проверки условия. 

К примеру в коде выше можно сделать так:
Метод должен выйти с ошибкой если модель не валидна

**Comment by barnet30** [comment]
Поправил
