### ISSUE TITLE
Использование асинхронности в коде

### ISSUE THREAD

**Issue by pingvin1308** [barnet30/scheduler#7]
https://github.com/barnet30/scheduler/blob/59909b8322f89de06767d74031031ef8095caf81/scheduler/Controllers/DateEventController.cs#L68

Закрадывается подозрение, что есть непонимание что такое асинхронность и как ей пользоваться.
В коде случайным образом присутствуют конструкции async\await.

Думаю следует восполнить данный пробел, так как почти весь современный код пишется с учетом работы с асихронностью и многопоточностью.

**Comment by barnet30** [comment]
поправил
