### ISSUE TITLE
Убрать использование query синтаксиса для linq выражений

### ISSUE THREAD

**Issue by pingvin1308** [barnet30/scheduler#8]
https://github.com/barnet30/scheduler/blob/59909b8322f89de06767d74031031ef8095caf81/scheduler/Controllers/EventController.cs#L97

Обычно используют только один стиль написание linq выражений. Так как в query синтаксис уже сильно отстает и в нем нету многих конструкций следует придерживаться стиля написания через Extension методы)

**Comment by pingvin1308** [comment]
Ну и название переменой непонятное -_-

**Comment by barnet30** [comment]
Поправил
