### ISSUE TITLE
Слишком абстрактное название метода

### ISSUE THREAD

**Issue by pingvin1308** [barnet30/scheduler#9]
https://github.com/barnet30/scheduler/blob/59909b8322f89de06767d74031031ef8095caf81/scheduler/Controllers/EventController.cs#L91

К сожаление контекст кода плохо подсказывает что именно будет вычисляться. Тут либо определять отдельный класс, в котором будет логика вычисления подходящей даты, либо написать название метода так, чтобы сразу было понятно

**Comment by barnet30** [comment]
Изменил название
